# Generated by Django 4.1.4 on 2022-12-10 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('income', models.IntegerField()),
                ('noOfFamilyMembers', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.FloatField()),
                ('soilType', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='FieldImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='uploads/')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='microApp.field')),
            ],
        ),
    ]
